AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Happy Birthday Application Backend

Resources:
  # API Gateway
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # Lambda Functions
  GetMemoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: getMemories.handler
      Runtime: nodejs18.x
      Events:
        GetMemories:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /memories
            Method: get

  CreateMemoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: createMemory.handler
      Runtime: nodejs18.x
      Events:
        CreateMemory:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /memories
            Method: post

  # DynamoDB Table
  MemoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Memories
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/" 